### ISSUE TITLE
postRequest.setPostDateGmt(calendar.getTime()); 设置时间时报错.

### ISSUE THREAD

**Issue by jorton** [zhyea/wordpress-client#1]
Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
postRequest.setPostDateGmt(calendar.getTime());
报错信息为: 
org.apache.xmlrpc.common.XmlRpcExtensionException: Long values aren't supported, if isEnabledForExtensions() == false

**Comment by zhyea** [comment]
> Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
> postRequest.setPostDateGmt(calendar.getTime());
> 报错信息为:
> org.apache.xmlrpc.common.XmlRpcExtensionException: Long values aren't supported, if isEnabledForExtensions() == false

您这类型用错了。我更新了一下，兼容了长整型。

**Comment by zhyea** [comment]
使用ide这种错误通常都可以及时发现

**Comment by jorton** [comment]
这种不是编译的时候报错, 是在发送请求了以后返回的错误.
开始我使用的是 postRequest.setPostDateGmt(new Date()); 请求后有问题.
我以为gmt需要单独的获取又换了这种方式
Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
postRequest.setPostDateGmt(calendar.getTime());

目前使用版本
<version>0.1.5</version>
发送请求还是这个错误.

Caused by: org.apache.xmlrpc.common.XmlRpcExtensionException: Long values aren't supported, if isEnabledForExtensions() == false

还去麻烦看一下.

**Comment by jorton** [comment]
这个是请求完返回的完整错误.

Caused by: org.apache.xmlrpc.common.XmlRpcExtensionException: Long values aren't supported, if isEnabledForExtensions() == false
	at org.apache.xmlrpc.common.TypeFactoryImpl.getSerializer(TypeFactoryImpl.java:140)
	at org.apache.xmlrpc.serializer.MapSerializer.writeValue(MapSerializer.java:73)
	at org.apache.xmlrpc.serializer.MapSerializer.writeEntry(MapSerializer.java:67)
	at org.apache.xmlrpc.serializer.MapSerializer.writeData(MapSerializer.java:84)
	at org.apache.xmlrpc.serializer.MapSerializer.write(MapSerializer.java:91)
	at org.apache.xmlrpc.serializer.XmlRpcWriter.writeValue(XmlRpcWriter.java:175)
	at org.apache.xmlrpc.serializer.XmlRpcWriter.write(XmlRpcWriter.java:80)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport$ReqWriterImpl.write(XmlRpcStreamTransport.java:70)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport$ByteArrayReqWriter.<init>(XmlRpcHttpTransport.java:45)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.newReqWriter(XmlRpcHttpTransport.java:155)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:150)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.chobit.wp.WPClient.execute(WPClient.java:141)
	at org.chobit.wp.WPClient.execute(WPClient.java:129)
	at org.chobit.wp.WPClient.editPost(WPClient.java:69)
	at org.chobit.wp.WordPress.editPost(WordPress.java:107)
	... 12 more
